/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_myapp_JNIS */

#ifndef _Included_com_example_administrator_myapp_JNIS
#define _Included_com_example_administrator_myapp_JNIS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_myapp_JNIS
 * Method:    helloJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_com_example_administrator_myapp_JNIS_helloJNI(JNIEnv*, jobject);

JNIEXPORT jstring JNICALL
Java_com_example_administrator_myapp_JNIS_checkPwd(JNIEnv*, jobject, jstring);

JNIEXPORT void JNICALL Java_com_example_administrator_myapp_MainActivity_callbackShowToast
        (JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
